version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      github-actions-routine:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      docker-routine:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      python-routine:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
